/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';

/**
 * 
 * @export
 * @interface Accounts
 */
export interface Accounts {
    /**
     * 
     * @type {Array<Account>}
     * @memberof Accounts
     */
    accounts: Array<Account>;
}

/**
 * Check if a given object implements the Accounts interface.
 */
export function instanceOfAccounts(value: object): value is Accounts {
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function AccountsFromJSON(json: any): Accounts {
    return AccountsFromJSONTyped(json, false);
}

export function AccountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Accounts {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': ((json['accounts'] as Array<any>).map(AccountFromJSON)),
    };
}

export function AccountsToJSON(value?: Accounts | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accounts': ((value['accounts'] as Array<any>).map(AccountToJSON)),
    };
}

