/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressParse200ResponseBounceable
 */
export interface AddressParse200ResponseBounceable {
    /**
     * 
     * @type {string}
     * @memberof AddressParse200ResponseBounceable
     */
    b64: string;
    /**
     * 
     * @type {string}
     * @memberof AddressParse200ResponseBounceable
     */
    b64url: string;
}

/**
 * Check if a given object implements the AddressParse200ResponseBounceable interface.
 */
export function instanceOfAddressParse200ResponseBounceable(value: object): value is AddressParse200ResponseBounceable {
    if (!('b64' in value) || value['b64'] === undefined) return false;
    if (!('b64url' in value) || value['b64url'] === undefined) return false;
    return true;
}

export function AddressParse200ResponseBounceableFromJSON(json: any): AddressParse200ResponseBounceable {
    return AddressParse200ResponseBounceableFromJSONTyped(json, false);
}

export function AddressParse200ResponseBounceableFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressParse200ResponseBounceable {
    if (json == null) {
        return json;
    }
    return {
        
        'b64': json['b64'],
        'b64url': json['b64url'],
    };
}

export function AddressParse200ResponseBounceableToJSON(value?: AddressParse200ResponseBounceable | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'b64': value['b64'],
        'b64url': value['b64url'],
    };
}

