/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockchainBlock } from './BlockchainBlock';
import {
    BlockchainBlockFromJSON,
    BlockchainBlockFromJSONTyped,
    BlockchainBlockToJSON,
} from './BlockchainBlock';

/**
 * 
 * @export
 * @interface BlockchainBlocks
 */
export interface BlockchainBlocks {
    /**
     * 
     * @type {Array<BlockchainBlock>}
     * @memberof BlockchainBlocks
     */
    blocks: Array<BlockchainBlock>;
}

/**
 * Check if a given object implements the BlockchainBlocks interface.
 */
export function instanceOfBlockchainBlocks(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "blocks" in value;

    return isInstance;
}

export function BlockchainBlocksFromJSON(json: any): BlockchainBlocks {
    return BlockchainBlocksFromJSONTyped(json, false);
}

export function BlockchainBlocksFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainBlocks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blocks': ((json['blocks'] as Array<any>).map(BlockchainBlockFromJSON)),
    };
}

export function BlockchainBlocksToJSON(value?: BlockchainBlocks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blocks': ((value.blocks as Array<any>).map(BlockchainBlockToJSON)),
    };
}

