/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The cost of filing complaints about incorrect operation of validators.
 * @export
 * @interface BlockchainConfig13
 */
export interface BlockchainConfig13 {
    /**
     * 
     * @type {number}
     * @memberof BlockchainConfig13
     */
    deposit: number;
    /**
     * 
     * @type {number}
     * @memberof BlockchainConfig13
     */
    bitPrice: number;
    /**
     * 
     * @type {number}
     * @memberof BlockchainConfig13
     */
    cellPrice: number;
}

/**
 * Check if a given object implements the BlockchainConfig13 interface.
 */
export function instanceOfBlockchainConfig13(value: object): value is BlockchainConfig13 {
    if (!('deposit' in value) || value['deposit'] === undefined) return false;
    if (!('bitPrice' in value) || value['bitPrice'] === undefined) return false;
    if (!('cellPrice' in value) || value['cellPrice'] === undefined) return false;
    return true;
}

export function BlockchainConfig13FromJSON(json: any): BlockchainConfig13 {
    return BlockchainConfig13FromJSONTyped(json, false);
}

export function BlockchainConfig13FromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainConfig13 {
    if (json == null) {
        return json;
    }
    return {
        
        'deposit': json['deposit'],
        'bitPrice': json['bit_price'],
        'cellPrice': json['cell_price'],
    };
}

export function BlockchainConfig13ToJSON(value?: BlockchainConfig13 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'deposit': value['deposit'],
        'bit_price': value['bitPrice'],
        'cell_price': value['cellPrice'],
    };
}

