/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockchainLibrary
 */
export interface BlockchainLibrary {
    /**
     * 
     * @type {string}
     * @memberof BlockchainLibrary
     */
    boc: string;
}

/**
 * Check if a given object implements the BlockchainLibrary interface.
 */
export function instanceOfBlockchainLibrary(value: object): value is BlockchainLibrary {
    if (!('boc' in value) || value['boc'] === undefined) return false;
    return true;
}

export function BlockchainLibraryFromJSON(json: any): BlockchainLibrary {
    return BlockchainLibraryFromJSONTyped(json, false);
}

export function BlockchainLibraryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainLibrary {
    if (json == null) {
        return json;
    }
    return {
        
        'boc': json['boc'],
    };
}

  export function BlockchainLibraryToJSON(json: any): BlockchainLibrary {
      return BlockchainLibraryToJSONTyped(json, false);
  }

  export function BlockchainLibraryToJSONTyped(value?: BlockchainLibrary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boc': value['boc'],
    };
}

