/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountStorageInfo } from './AccountStorageInfo';
import {
    AccountStorageInfoFromJSON,
    AccountStorageInfoFromJSONTyped,
    AccountStorageInfoToJSON,
} from './AccountStorageInfo';

/**
 * 
 * @export
 * @interface BlockchainRawAccount
 */
export interface BlockchainRawAccount {
    /**
     * 
     * @type {string}
     * @memberof BlockchainRawAccount
     */
    address: string;
    /**
     * 
     * @type {number}
     * @memberof BlockchainRawAccount
     */
    balance: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof BlockchainRawAccount
     */
    extraBalance?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof BlockchainRawAccount
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockchainRawAccount
     */
    data?: string;
    /**
     * 
     * @type {number}
     * @memberof BlockchainRawAccount
     */
    lastTransactionLt: number;
    /**
     * 
     * @type {string}
     * @memberof BlockchainRawAccount
     */
    status: string;
    /**
     * 
     * @type {AccountStorageInfo}
     * @memberof BlockchainRawAccount
     */
    storage: AccountStorageInfo;
}

/**
 * Check if a given object implements the BlockchainRawAccount interface.
 */
export function instanceOfBlockchainRawAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "balance" in value;
    isInstance = isInstance && "lastTransactionLt" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "storage" in value;

    return isInstance;
}

export function BlockchainRawAccountFromJSON(json: any): BlockchainRawAccount {
    return BlockchainRawAccountFromJSONTyped(json, false);
}

export function BlockchainRawAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainRawAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'balance': json['balance'],
        'extraBalance': !exists(json, 'extra_balance') ? undefined : json['extra_balance'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'lastTransactionLt': json['last_transaction_lt'],
        'status': json['status'],
        'storage': AccountStorageInfoFromJSON(json['storage']),
    };
}

export function BlockchainRawAccountToJSON(value?: BlockchainRawAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'balance': value.balance,
        'extra_balance': value.extraBalance,
        'code': value.code,
        'data': value.data,
        'last_transaction_lt': value.lastTransactionLt,
        'status': value.status,
        'storage': AccountStorageInfoToJSON(value.storage),
    };
}

