/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockLimits } from './BlockLimits';
import {
    BlockLimitsFromJSON,
    BlockLimitsFromJSONTyped,
    BlockLimitsToJSON,
} from './BlockLimits';

/**
 * The limits on the block in the masterchain, upon reaching which the block is finalized and the callback of the remaining messages (if any) is carried over to the next block.
 * @export
 * @interface BlockchainConfig22
 */
export interface BlockchainConfig22 {
    /**
     * 
     * @type {BlockLimits}
     * @memberof BlockchainConfig22
     */
    blockLimits: BlockLimits;
}

/**
 * Check if a given object implements the BlockchainConfig22 interface.
 */
export function instanceOfBlockchainConfig22(value: object): value is BlockchainConfig22 {
    if (!('blockLimits' in value) || value['blockLimits'] === undefined) return false;
    return true;
}

export function BlockchainConfig22FromJSON(json: any): BlockchainConfig22 {
    return BlockchainConfig22FromJSONTyped(json, false);
}

export function BlockchainConfig22FromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainConfig22 {
    if (json == null) {
        return json;
    }
    return {
        
        'blockLimits': BlockLimitsFromJSON(json['block_limits']),
    };
}

export function BlockchainConfig22ToJSON(value?: BlockchainConfig22 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'block_limits': BlockLimitsToJSON(value['blockLimits']),
    };
}

