/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockchainBlockShardsShardsInner
 */
export interface BlockchainBlockShardsShardsInner {
    /**
     * 
     * @type {string}
     * @memberof BlockchainBlockShardsShardsInner
     */
    lastKnownBlockId: string;
}

/**
 * Check if a given object implements the BlockchainBlockShardsShardsInner interface.
 */
export function instanceOfBlockchainBlockShardsShardsInner(value: object): boolean {
    if (!('lastKnownBlockId' in value)) return false;
    return true;
}

export function BlockchainBlockShardsShardsInnerFromJSON(json: any): BlockchainBlockShardsShardsInner {
    return BlockchainBlockShardsShardsInnerFromJSONTyped(json, false);
}

export function BlockchainBlockShardsShardsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainBlockShardsShardsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'lastKnownBlockId': json['last_known_block_id'],
    };
}

export function BlockchainBlockShardsShardsInnerToJSON(value?: BlockchainBlockShardsShardsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'last_known_block_id': value['lastKnownBlockId'],
    };
}

