/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecodeMessageRequest
 */
export interface DecodeMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof DecodeMessageRequest
     */
    boc: string;
}

/**
 * Check if a given object implements the DecodeMessageRequest interface.
 */
export function instanceOfDecodeMessageRequest(value: object): value is DecodeMessageRequest {
    if (!('boc' in value) || value['boc'] === undefined) return false;
    return true;
}

export function DecodeMessageRequestFromJSON(json: any): DecodeMessageRequest {
    return DecodeMessageRequestFromJSONTyped(json, false);
}

export function DecodeMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodeMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'boc': json['boc'],
    };
}

export function DecodeMessageRequestToJSON(value?: DecodeMessageRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'boc': value['boc'],
    };
}

