/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExecGetMethodArgType } from './ExecGetMethodArgType';
import {
    ExecGetMethodArgTypeFromJSON,
    ExecGetMethodArgTypeFromJSONTyped,
    ExecGetMethodArgTypeToJSON,
    ExecGetMethodArgTypeToJSONTyped,
} from './ExecGetMethodArgType';

/**
 * 
 * @export
 * @interface ExecGetMethodArg
 */
export interface ExecGetMethodArg {
    /**
     * 
     * @type {ExecGetMethodArgType}
     * @memberof ExecGetMethodArg
     */
    type: ExecGetMethodArgType;
    /**
     * String representation of the value according to the specified type
     * @type {string}
     * @memberof ExecGetMethodArg
     */
    value: string;
}



/**
 * Check if a given object implements the ExecGetMethodArg interface.
 */
export function instanceOfExecGetMethodArg(value: object): value is ExecGetMethodArg {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ExecGetMethodArgFromJSON(json: any): ExecGetMethodArg {
    return ExecGetMethodArgFromJSONTyped(json, false);
}

export function ExecGetMethodArgFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecGetMethodArg {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ExecGetMethodArgTypeFromJSON(json['type']),
        'value': json['value'],
    };
}

  export function ExecGetMethodArgToJSON(json: any): ExecGetMethodArg {
      return ExecGetMethodArgToJSONTyped(json, false);
  }

  export function ExecGetMethodArgToJSONTyped(value?: ExecGetMethodArg | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ExecGetMethodArgTypeToJSON(value['type']),
        'value': value['value'],
    };
}

