/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EcPreview } from './EcPreview';
import {
    EcPreviewFromJSON,
    EcPreviewFromJSONTyped,
    EcPreviewToJSON,
    EcPreviewToJSONTyped,
} from './EcPreview';

/**
 * 
 * @export
 * @interface ExtraCurrency
 */
export interface ExtraCurrency {
    /**
     * 
     * @type {string}
     * @memberof ExtraCurrency
     */
    amount: string;
    /**
     * 
     * @type {EcPreview}
     * @memberof ExtraCurrency
     */
    preview: EcPreview;
}

/**
 * Check if a given object implements the ExtraCurrency interface.
 */
export function instanceOfExtraCurrency(value: object): value is ExtraCurrency {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('preview' in value) || value['preview'] === undefined) return false;
    return true;
}

export function ExtraCurrencyFromJSON(json: any): ExtraCurrency {
    return ExtraCurrencyFromJSONTyped(json, false);
}

export function ExtraCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtraCurrency {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'preview': EcPreviewFromJSON(json['preview']),
    };
}

  export function ExtraCurrencyToJSON(json: any): ExtraCurrency {
      return ExtraCurrencyToJSONTyped(json, false);
  }

  export function ExtraCurrencyToJSONTyped(value?: ExtraCurrency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'preview': EcPreviewToJSON(value['preview']),
    };
}

