/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoundAccountsAddressesInner
 */
export interface FoundAccountsAddressesInner {
    /**
     * 
     * @type {string}
     * @memberof FoundAccountsAddressesInner
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof FoundAccountsAddressesInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FoundAccountsAddressesInner
     */
    preview: string;
}

/**
 * Check if a given object implements the FoundAccountsAddressesInner interface.
 */
export function instanceOfFoundAccountsAddressesInner(value: object): value is FoundAccountsAddressesInner {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('preview' in value) || value['preview'] === undefined) return false;
    return true;
}

export function FoundAccountsAddressesInnerFromJSON(json: any): FoundAccountsAddressesInner {
    return FoundAccountsAddressesInnerFromJSONTyped(json, false);
}

export function FoundAccountsAddressesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoundAccountsAddressesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'name': json['name'],
        'preview': json['preview'],
    };
}

export function FoundAccountsAddressesInnerToJSON(value?: FoundAccountsAddressesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'name': value['name'],
        'preview': value['preview'],
    };
}

