/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockRaw } from './BlockRaw';
import {
    BlockRawFromJSON,
    BlockRawFromJSONTyped,
    BlockRawToJSON,
} from './BlockRaw';

/**
 * 
 * @export
 * @interface GetAllRawShardsInfo200Response
 */
export interface GetAllRawShardsInfo200Response {
    /**
     * 
     * @type {BlockRaw}
     * @memberof GetAllRawShardsInfo200Response
     */
    id: BlockRaw;
    /**
     * 
     * @type {string}
     * @memberof GetAllRawShardsInfo200Response
     */
    proof: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllRawShardsInfo200Response
     */
    data: string;
}

/**
 * Check if a given object implements the GetAllRawShardsInfo200Response interface.
 */
export function instanceOfGetAllRawShardsInfo200Response(value: object): value is GetAllRawShardsInfo200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('proof' in value) || value['proof'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetAllRawShardsInfo200ResponseFromJSON(json: any): GetAllRawShardsInfo200Response {
    return GetAllRawShardsInfo200ResponseFromJSONTyped(json, false);
}

export function GetAllRawShardsInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllRawShardsInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': BlockRawFromJSON(json['id']),
        'proof': json['proof'],
        'data': json['data'],
    };
}

export function GetAllRawShardsInfo200ResponseToJSON(value?: GetAllRawShardsInfo200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': BlockRawToJSON(value['id']),
        'proof': value['proof'],
        'data': value['data'],
    };
}

