/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountDiff200Response
 */
export interface GetAccountDiff200Response {
    /**
     * 
     * @type {number}
     * @memberof GetAccountDiff200Response
     */
    balanceChange: number;
}

/**
 * Check if a given object implements the GetAccountDiff200Response interface.
 */
export function instanceOfGetAccountDiff200Response(value: object): value is GetAccountDiff200Response {
    if (!('balanceChange' in value) || value['balanceChange'] === undefined) return false;
    return true;
}

export function GetAccountDiff200ResponseFromJSON(json: any): GetAccountDiff200Response {
    return GetAccountDiff200ResponseFromJSONTyped(json, false);
}

export function GetAccountDiff200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountDiff200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'balanceChange': json['balance_change'],
    };
}

export function GetAccountDiff200ResponseToJSON(value?: GetAccountDiff200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'balance_change': value['balanceChange'],
    };
}

