/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetOutMsgQueueSizes200ResponseShardsInner } from './GetOutMsgQueueSizes200ResponseShardsInner';
import {
    GetOutMsgQueueSizes200ResponseShardsInnerFromJSON,
    GetOutMsgQueueSizes200ResponseShardsInnerFromJSONTyped,
    GetOutMsgQueueSizes200ResponseShardsInnerToJSON,
} from './GetOutMsgQueueSizes200ResponseShardsInner';

/**
 * 
 * @export
 * @interface GetOutMsgQueueSizes200Response
 */
export interface GetOutMsgQueueSizes200Response {
    /**
     * 
     * @type {number}
     * @memberof GetOutMsgQueueSizes200Response
     */
    extMsgQueueSizeLimit: number;
    /**
     * 
     * @type {Array<GetOutMsgQueueSizes200ResponseShardsInner>}
     * @memberof GetOutMsgQueueSizes200Response
     */
    shards: Array<GetOutMsgQueueSizes200ResponseShardsInner>;
}

/**
 * Check if a given object implements the GetOutMsgQueueSizes200Response interface.
 */
export function instanceOfGetOutMsgQueueSizes200Response(value: object): value is GetOutMsgQueueSizes200Response {
    if (!('extMsgQueueSizeLimit' in value) || value['extMsgQueueSizeLimit'] === undefined) return false;
    if (!('shards' in value) || value['shards'] === undefined) return false;
    return true;
}

export function GetOutMsgQueueSizes200ResponseFromJSON(json: any): GetOutMsgQueueSizes200Response {
    return GetOutMsgQueueSizes200ResponseFromJSONTyped(json, false);
}

export function GetOutMsgQueueSizes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOutMsgQueueSizes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'extMsgQueueSizeLimit': json['ext_msg_queue_size_limit'],
        'shards': ((json['shards'] as Array<any>).map(GetOutMsgQueueSizes200ResponseShardsInnerFromJSON)),
    };
}

export function GetOutMsgQueueSizes200ResponseToJSON(value?: GetOutMsgQueueSizes200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ext_msg_queue_size_limit': value['extMsgQueueSizeLimit'],
        'shards': ((value['shards'] as Array<any>).map(GetOutMsgQueueSizes200ResponseShardsInnerToJSON)),
    };
}

