/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockRaw } from './BlockRaw';
import {
    BlockRawFromJSON,
    BlockRawFromJSONTyped,
    BlockRawToJSON,
} from './BlockRaw';

/**
 * 
 * @export
 * @interface GetRawBlockchainBlockHeader200Response
 */
export interface GetRawBlockchainBlockHeader200Response {
    /**
     * 
     * @type {BlockRaw}
     * @memberof GetRawBlockchainBlockHeader200Response
     */
    id: BlockRaw;
    /**
     * 
     * @type {number}
     * @memberof GetRawBlockchainBlockHeader200Response
     */
    mode: number;
    /**
     * 
     * @type {string}
     * @memberof GetRawBlockchainBlockHeader200Response
     */
    headerProof: string;
}

/**
 * Check if a given object implements the GetRawBlockchainBlockHeader200Response interface.
 */
export function instanceOfGetRawBlockchainBlockHeader200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "mode" in value;
    isInstance = isInstance && "headerProof" in value;

    return isInstance;
}

export function GetRawBlockchainBlockHeader200ResponseFromJSON(json: any): GetRawBlockchainBlockHeader200Response {
    return GetRawBlockchainBlockHeader200ResponseFromJSONTyped(json, false);
}

export function GetRawBlockchainBlockHeader200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRawBlockchainBlockHeader200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': BlockRawFromJSON(json['id']),
        'mode': json['mode'],
        'headerProof': json['header_proof'],
    };
}

export function GetRawBlockchainBlockHeader200ResponseToJSON(value?: GetRawBlockchainBlockHeader200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': BlockRawToJSON(value.id),
        'mode': value.mode,
        'header_proof': value.headerProof,
    };
}

