/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InitStateRaw
 */
export interface InitStateRaw {
    /**
     * 
     * @type {number}
     * @memberof InitStateRaw
     */
    workchain: number;
    /**
     * 
     * @type {string}
     * @memberof InitStateRaw
     */
    rootHash: string;
    /**
     * 
     * @type {string}
     * @memberof InitStateRaw
     */
    fileHash: string;
}

/**
 * Check if a given object implements the InitStateRaw interface.
 */
export function instanceOfInitStateRaw(value: object): value is InitStateRaw {
    if (!('workchain' in value) || value['workchain'] === undefined) return false;
    if (!('rootHash' in value) || value['rootHash'] === undefined) return false;
    if (!('fileHash' in value) || value['fileHash'] === undefined) return false;
    return true;
}

export function InitStateRawFromJSON(json: any): InitStateRaw {
    return InitStateRawFromJSONTyped(json, false);
}

export function InitStateRawFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitStateRaw {
    if (json == null) {
        return json;
    }
    return {
        
        'workchain': json['workchain'],
        'rootHash': json['root_hash'],
        'fileHash': json['file_hash'],
    };
}

export function InitStateRawToJSON(value?: InitStateRaw | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'workchain': value['workchain'],
        'root_hash': value['rootHash'],
        'file_hash': value['fileHash'],
    };
}

