/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
} from './AccountAddress';
import type { JettonPreview } from './JettonPreview';
import {
    JettonPreviewFromJSON,
    JettonPreviewFromJSONTyped,
    JettonPreviewToJSON,
} from './JettonPreview';

/**
 * 
 * @export
 * @interface JettonBurnAction
 */
export interface JettonBurnAction {
    /**
     * 
     * @type {AccountAddress}
     * @memberof JettonBurnAction
     */
    sender: AccountAddress;
    /**
     * 
     * @type {string}
     * @memberof JettonBurnAction
     */
    sendersWallet: string;
    /**
     * amount in quanta of tokens
     * @type {string}
     * @memberof JettonBurnAction
     */
    amount: string;
    /**
     * 
     * @type {JettonPreview}
     * @memberof JettonBurnAction
     */
    jetton: JettonPreview;
}

/**
 * Check if a given object implements the JettonBurnAction interface.
 */
export function instanceOfJettonBurnAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sender" in value;
    isInstance = isInstance && "sendersWallet" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "jetton" in value;

    return isInstance;
}

export function JettonBurnActionFromJSON(json: any): JettonBurnAction {
    return JettonBurnActionFromJSONTyped(json, false);
}

export function JettonBurnActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonBurnAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sender': AccountAddressFromJSON(json['sender']),
        'sendersWallet': json['senders_wallet'],
        'amount': json['amount'],
        'jetton': JettonPreviewFromJSON(json['jetton']),
    };
}

export function JettonBurnActionToJSON(value?: JettonBurnAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sender': AccountAddressToJSON(value.sender),
        'senders_wallet': value.sendersWallet,
        'amount': value.amount,
        'jetton': JettonPreviewToJSON(value.jetton),
    };
}

