/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JettonBridgePrices
 */
export interface JettonBridgePrices {
    /**
     * 
     * @type {number}
     * @memberof JettonBridgePrices
     */
    bridgeBurnFee: number;
    /**
     * 
     * @type {number}
     * @memberof JettonBridgePrices
     */
    bridgeMintFee: number;
    /**
     * 
     * @type {number}
     * @memberof JettonBridgePrices
     */
    walletMinTonsForStorage: number;
    /**
     * 
     * @type {number}
     * @memberof JettonBridgePrices
     */
    walletGasConsumption: number;
    /**
     * 
     * @type {number}
     * @memberof JettonBridgePrices
     */
    minterMinTonsForStorage: number;
    /**
     * 
     * @type {number}
     * @memberof JettonBridgePrices
     */
    discoverGasConsumption: number;
}

/**
 * Check if a given object implements the JettonBridgePrices interface.
 */
export function instanceOfJettonBridgePrices(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "bridgeBurnFee" in value;
    isInstance = isInstance && "bridgeMintFee" in value;
    isInstance = isInstance && "walletMinTonsForStorage" in value;
    isInstance = isInstance && "walletGasConsumption" in value;
    isInstance = isInstance && "minterMinTonsForStorage" in value;
    isInstance = isInstance && "discoverGasConsumption" in value;

    return isInstance;
}

export function JettonBridgePricesFromJSON(json: any): JettonBridgePrices {
    return JettonBridgePricesFromJSONTyped(json, false);
}

export function JettonBridgePricesFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonBridgePrices {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bridgeBurnFee': json['bridge_burn_fee'],
        'bridgeMintFee': json['bridge_mint_fee'],
        'walletMinTonsForStorage': json['wallet_min_tons_for_storage'],
        'walletGasConsumption': json['wallet_gas_consumption'],
        'minterMinTonsForStorage': json['minter_min_tons_for_storage'],
        'discoverGasConsumption': json['discover_gas_consumption'],
    };
}

export function JettonBridgePricesToJSON(value?: JettonBridgePrices | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bridge_burn_fee': value.bridgeBurnFee,
        'bridge_mint_fee': value.bridgeMintFee,
        'wallet_min_tons_for_storage': value.walletMinTonsForStorage,
        'wallet_gas_consumption': value.walletGasConsumption,
        'minter_min_tons_for_storage': value.minterMinTonsForStorage,
        'discover_gas_consumption': value.discoverGasConsumption,
    };
}

