/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JettonInfo } from './JettonInfo';
import {
    JettonInfoFromJSON,
    JettonInfoFromJSONTyped,
    JettonInfoToJSON,
} from './JettonInfo';

/**
 * 
 * @export
 * @interface Jettons
 */
export interface Jettons {
    /**
     * 
     * @type {Array<JettonInfo>}
     * @memberof Jettons
     */
    jettons: Array<JettonInfo>;
}

/**
 * Check if a given object implements the Jettons interface.
 */
export function instanceOfJettons(value: object): value is Jettons {
    if (!('jettons' in value) || value['jettons'] === undefined) return false;
    return true;
}

export function JettonsFromJSON(json: any): Jettons {
    return JettonsFromJSONTyped(json, false);
}

export function JettonsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Jettons {
    if (json == null) {
        return json;
    }
    return {
        
        'jettons': ((json['jettons'] as Array<any>).map(JettonInfoFromJSON)),
    };
}

export function JettonsToJSON(value?: Jettons | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jettons': ((value['jettons'] as Array<any>).map(JettonInfoToJSON)),
    };
}

