/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignRawMessage
 */
export interface SignRawMessage {
    /**
     * 
     * @type {string}
     * @memberof SignRawMessage
     */
    address: string;
    /**
     * Number of nanocoins to send. Decimal string.
     * @type {string}
     * @memberof SignRawMessage
     */
    amount: string;
    /**
     * Raw one-cell BoC encoded in hex.
     * @type {string}
     * @memberof SignRawMessage
     */
    payload?: string;
    /**
     * Raw once-cell BoC encoded in hex.
     * @type {string}
     * @memberof SignRawMessage
     */
    stateInit?: string;
}

/**
 * Check if a given object implements the SignRawMessage interface.
 */
export function instanceOfSignRawMessage(value: object): value is SignRawMessage {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function SignRawMessageFromJSON(json: any): SignRawMessage {
    return SignRawMessageFromJSONTyped(json, false);
}

export function SignRawMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignRawMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'amount': json['amount'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'stateInit': json['stateInit'] == null ? undefined : json['stateInit'],
    };
}

export function SignRawMessageToJSON(value?: SignRawMessage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'amount': value['amount'],
        'payload': value['payload'],
        'stateInit': value['stateInit'],
    };
}

