/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SourceFile } from './SourceFile';
import {
    SourceFileFromJSON,
    SourceFileFromJSONTyped,
    SourceFileToJSON,
    SourceFileToJSONTyped,
} from './SourceFile';

/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * 
     * @type {Array<SourceFile>}
     * @memberof Source
     */
    files: Array<SourceFile>;
}

/**
 * Check if a given object implements the Source interface.
 */
export function instanceOfSource(value: object): value is Source {
    if (!('files' in value) || value['files'] === undefined) return false;
    return true;
}

export function SourceFromJSON(json: any): Source {
    return SourceFromJSONTyped(json, false);
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
    if (json == null) {
        return json;
    }
    return {
        
        'files': ((json['files'] as Array<any>).map(SourceFileFromJSON)),
    };
}

  export function SourceToJSON(json: any): Source {
      return SourceToJSONTyped(json, false);
  }

  export function SourceToJSONTyped(value?: Source | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'files': ((value['files'] as Array<any>).map(SourceFileToJSON)),
    };
}

