/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StateInit
 */
export interface StateInit {
    /**
     * 
     * @type {string}
     * @memberof StateInit
     */
    boc: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StateInit
     */
    interfaces: Array<string>;
}

/**
 * Check if a given object implements the StateInit interface.
 */
export function instanceOfStateInit(value: object): value is StateInit {
    if (!('boc' in value) || value['boc'] === undefined) return false;
    if (!('interfaces' in value) || value['interfaces'] === undefined) return false;
    return true;
}

export function StateInitFromJSON(json: any): StateInit {
    return StateInitFromJSONTyped(json, false);
}

export function StateInitFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateInit {
    if (json == null) {
        return json;
    }
    return {
        
        'boc': json['boc'],
        'interfaces': json['interfaces'],
    };
}

export function StateInitToJSON(value?: StateInit | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'boc': value['boc'],
        'interfaces': value['interfaces'],
    };
}

