/* tslint:disable */
/* eslint-disable */
/**
 * REST api to TON blockchain explorer
 * Provide access to indexed TON blockchain
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusDefaultResponse
 */
export interface StatusDefaultResponse {
    /**
     * 
     * @type {string}
     * @memberof StatusDefaultResponse
     */
    error: string;
}

/**
 * Check if a given object implements the StatusDefaultResponse interface.
 */
export function instanceOfStatusDefaultResponse(value: object): value is StatusDefaultResponse {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function StatusDefaultResponseFromJSON(json: any): StatusDefaultResponse {
    return StatusDefaultResponseFromJSONTyped(json, false);
}

export function StatusDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusDefaultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function StatusDefaultResponseToJSON(value?: StatusDefaultResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

