export * from './MainPromoRuIcon';
export * from './SupportPromoRuIcon';
export * from './MultiSendPromoRuIcon';
export * from './MultiWalletPromoRuIcon';
export * from './MainPromoEnIcon';
export * from './SupportPromoEnIcon';
export * from './MultiSigPromoEnIcon';
export * from './MultiSendPromoEnIcon';
export * from './MultiWalletPromoEnIcon';
