/* tslint:disable */
/* eslint-disable */
/**
 * Tonkeeper TWA API.
 * REST API for Tonkeeper TWA.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountEventsSubscriptionStatus200Response
 */
export interface AccountEventsSubscriptionStatus200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AccountEventsSubscriptionStatus200Response
     */
    subscribed: boolean;
}

/**
 * Check if a given object implements the AccountEventsSubscriptionStatus200Response interface.
 */
export function instanceOfAccountEventsSubscriptionStatus200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "subscribed" in value;

    return isInstance;
}

export function AccountEventsSubscriptionStatus200ResponseFromJSON(json: any): AccountEventsSubscriptionStatus200Response {
    return AccountEventsSubscriptionStatus200ResponseFromJSONTyped(json, false);
}

export function AccountEventsSubscriptionStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountEventsSubscriptionStatus200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subscribed': json['subscribed'],
    };
}

export function AccountEventsSubscriptionStatus200ResponseToJSON(value?: AccountEventsSubscriptionStatus200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subscribed': value.subscribed,
    };
}

