FROM openapitools/openapi-generator-cli

CMD ["generate", "-i", "https://raw.githubusercontent.com/tonkeeper/tonkeeper-twa-api/main/api/tonkeeper-twa-api.yml?token=GHSAT0AAAAAAB77BKLNGA4VMIRF3DFQU3XYZIVVYAQ", "-g", "typescript-fetch", "-o", "/local/src/twaApi", "-p", "supportsES6=true,withInterfaces=true"]