export enum AppKey {
    ACCOUNT = 'ACCOUNT',
    WALLET = 'WALLET',
    MNEMONIC = 'MNEMONIC',

    THEME = 'THEME',

    PASSWORD = 'PASSWORD',
    LOCK = 'LOCK',

    FAVOURITES = 'FAVOURITES',
    CONNECTIONS = 'CONNECTIONS',
    HIDDEN_SUGGESTIONS = 'HIDDEN_SUGGESTIONS',
    SYNC_DATE = 'SYNC_DATE'
}
