/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CategoryType = {
    Buy: 'buy',
    Sell: 'sell',
    Swap: 'swap',
    BuyUsdt: 'buy_usdt',
    SellUsdt: 'sell_usdt',
    BuyUsdtTrc20: 'buy_usdt_trc20',
    SellUsdtTrc20: 'sell_usdt_trc20',
    SellNot: 'sell_not',
    BuyNot: 'buy_not',
    SellHmstr: 'sell_hmstr',
    BuyHmstr: 'buy_hmstr'
} as const;
export type CategoryType = typeof CategoryType[keyof typeof CategoryType];


export function instanceOfCategoryType(value: any): boolean {
    for (const key in CategoryType) {
        if (Object.prototype.hasOwnProperty.call(CategoryType, key)) {
            if (CategoryType[key as keyof typeof CategoryType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CategoryTypeFromJSON(json: any): CategoryType {
    return CategoryTypeFromJSONTyped(json, false);
}

export function CategoryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryType {
    return json as CategoryType;
}

export function CategoryTypeToJSON(value?: CategoryType | null): any {
    return value as any;
}

export function CategoryTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CategoryType {
    return value as CategoryType;
}

