/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetType } from './AssetType';
import {
    AssetTypeFromJSON,
    AssetTypeFromJSONTyped,
    AssetTypeToJSON,
    AssetTypeToJSONTyped,
} from './AssetType';
import type { FiatCategoryItemsInnerSuccessUrlPattern } from './FiatCategoryItemsInnerSuccessUrlPattern';
import {
    FiatCategoryItemsInnerSuccessUrlPatternFromJSON,
    FiatCategoryItemsInnerSuccessUrlPatternFromJSONTyped,
    FiatCategoryItemsInnerSuccessUrlPatternToJSON,
    FiatCategoryItemsInnerSuccessUrlPatternToJSONTyped,
} from './FiatCategoryItemsInnerSuccessUrlPattern';
import type { FiatCategoryItemsInnerActionButton } from './FiatCategoryItemsInnerActionButton';
import {
    FiatCategoryItemsInnerActionButtonFromJSON,
    FiatCategoryItemsInnerActionButtonFromJSONTyped,
    FiatCategoryItemsInnerActionButtonToJSON,
    FiatCategoryItemsInnerActionButtonToJSONTyped,
} from './FiatCategoryItemsInnerActionButton';
import type { FiatCategoryItemsInnerInfoButtonsInner } from './FiatCategoryItemsInnerInfoButtonsInner';
import {
    FiatCategoryItemsInnerInfoButtonsInnerFromJSON,
    FiatCategoryItemsInnerInfoButtonsInnerFromJSONTyped,
    FiatCategoryItemsInnerInfoButtonsInnerToJSON,
    FiatCategoryItemsInnerInfoButtonsInnerToJSONTyped,
} from './FiatCategoryItemsInnerInfoButtonsInner';

/**
 * 
 * @export
 * @interface FiatCategoryItemsInner
 */
export interface FiatCategoryItemsInner {
    /**
     * 
     * @type {string}
     * @memberof FiatCategoryItemsInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FiatCategoryItemsInner
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof FiatCategoryItemsInner
     */
    disabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof FiatCategoryItemsInner
     */
    badge?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FiatCategoryItemsInner
     */
    subtitle: string;
    /**
     * 
     * @type {string}
     * @memberof FiatCategoryItemsInner
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof FiatCategoryItemsInner
     */
    iconUrl: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FiatCategoryItemsInner
     */
    features?: Array<string>;
    /**
     * 
     * @type {Array<AssetType>}
     * @memberof FiatCategoryItemsInner
     */
    assets?: Array<AssetType>;
    /**
     * 
     * @type {FiatCategoryItemsInnerActionButton}
     * @memberof FiatCategoryItemsInner
     */
    actionButton: FiatCategoryItemsInnerActionButton;
    /**
     * 
     * @type {FiatCategoryItemsInnerSuccessUrlPattern}
     * @memberof FiatCategoryItemsInner
     */
    successUrlPattern?: FiatCategoryItemsInnerSuccessUrlPattern;
    /**
     * 
     * @type {Array<FiatCategoryItemsInnerInfoButtonsInner>}
     * @memberof FiatCategoryItemsInner
     */
    infoButtons?: Array<FiatCategoryItemsInnerInfoButtonsInner>;
}

/**
 * Check if a given object implements the FiatCategoryItemsInner interface.
 */
export function instanceOfFiatCategoryItemsInner(value: object): value is FiatCategoryItemsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    if (!('subtitle' in value) || value['subtitle'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('iconUrl' in value) || value['iconUrl'] === undefined) return false;
    if (!('actionButton' in value) || value['actionButton'] === undefined) return false;
    return true;
}

export function FiatCategoryItemsInnerFromJSON(json: any): FiatCategoryItemsInner {
    return FiatCategoryItemsInnerFromJSONTyped(json, false);
}

export function FiatCategoryItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiatCategoryItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'disabled': json['disabled'],
        'badge': json['badge'] == null ? undefined : json['badge'],
        'subtitle': json['subtitle'],
        'description': json['description'],
        'iconUrl': json['icon_url'],
        'features': json['features'] == null ? undefined : json['features'],
        'assets': json['assets'] == null ? undefined : ((json['assets'] as Array<any>).map(AssetTypeFromJSON)),
        'actionButton': FiatCategoryItemsInnerActionButtonFromJSON(json['action_button']),
        'successUrlPattern': json['successUrlPattern'] == null ? undefined : FiatCategoryItemsInnerSuccessUrlPatternFromJSON(json['successUrlPattern']),
        'infoButtons': json['info_buttons'] == null ? undefined : ((json['info_buttons'] as Array<any>).map(FiatCategoryItemsInnerInfoButtonsInnerFromJSON)),
    };
}

export function FiatCategoryItemsInnerToJSON(json: any): FiatCategoryItemsInner {
    return FiatCategoryItemsInnerToJSONTyped(json, false);
}

export function FiatCategoryItemsInnerToJSONTyped(value?: FiatCategoryItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'disabled': value['disabled'],
        'badge': value['badge'],
        'subtitle': value['subtitle'],
        'description': value['description'],
        'icon_url': value['iconUrl'],
        'features': value['features'],
        'assets': value['assets'] == null ? undefined : ((value['assets'] as Array<any>).map(AssetTypeToJSON)),
        'action_button': FiatCategoryItemsInnerActionButtonToJSON(value['actionButton']),
        'successUrlPattern': FiatCategoryItemsInnerSuccessUrlPatternToJSON(value['successUrlPattern']),
        'info_buttons': value['infoButtons'] == null ? undefined : ((value['infoButtons'] as Array<any>).map(FiatCategoryItemsInnerInfoButtonsInnerToJSON)),
    };
}

