/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetFiatMethods200ResponseData } from './GetFiatMethods200ResponseData';
import {
    GetFiatMethods200ResponseDataFromJSON,
    GetFiatMethods200ResponseDataFromJSONTyped,
    GetFiatMethods200ResponseDataToJSON,
    GetFiatMethods200ResponseDataToJSONTyped,
} from './GetFiatMethods200ResponseData';

/**
 * 
 * @export
 * @interface GetFiatMethods200Response
 */
export interface GetFiatMethods200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetFiatMethods200Response
     */
    success: boolean;
    /**
     * 
     * @type {GetFiatMethods200ResponseData}
     * @memberof GetFiatMethods200Response
     */
    data?: GetFiatMethods200ResponseData;
}

/**
 * Check if a given object implements the GetFiatMethods200Response interface.
 */
export function instanceOfGetFiatMethods200Response(value: object): value is GetFiatMethods200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GetFiatMethods200ResponseFromJSON(json: any): GetFiatMethods200Response {
    return GetFiatMethods200ResponseFromJSONTyped(json, false);
}

export function GetFiatMethods200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFiatMethods200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'] == null ? undefined : GetFiatMethods200ResponseDataFromJSON(json['data']),
    };
}

export function GetFiatMethods200ResponseToJSON(json: any): GetFiatMethods200Response {
    return GetFiatMethods200ResponseToJSONTyped(json, false);
}

export function GetFiatMethods200ResponseToJSONTyped(value?: GetFiatMethods200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetFiatMethods200ResponseDataToJSON(value['data']),
    };
}

