/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFiatMethods200ResponseDataDefaultLayout
 */
export interface GetFiatMethods200ResponseDataDefaultLayout {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetFiatMethods200ResponseDataDefaultLayout
     */
    methods: Array<string>;
}

/**
 * Check if a given object implements the GetFiatMethods200ResponseDataDefaultLayout interface.
 */
export function instanceOfGetFiatMethods200ResponseDataDefaultLayout(value: object): value is GetFiatMethods200ResponseDataDefaultLayout {
    if (!('methods' in value) || value['methods'] === undefined) return false;
    return true;
}

export function GetFiatMethods200ResponseDataDefaultLayoutFromJSON(json: any): GetFiatMethods200ResponseDataDefaultLayout {
    return GetFiatMethods200ResponseDataDefaultLayoutFromJSONTyped(json, false);
}

export function GetFiatMethods200ResponseDataDefaultLayoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFiatMethods200ResponseDataDefaultLayout {
    if (json == null) {
        return json;
    }
    return {
        
        'methods': json['methods'],
    };
}

export function GetFiatMethods200ResponseDataDefaultLayoutToJSON(json: any): GetFiatMethods200ResponseDataDefaultLayout {
    return GetFiatMethods200ResponseDataDefaultLayoutToJSONTyped(json, false);
}

export function GetFiatMethods200ResponseDataDefaultLayoutToJSONTyped(value?: GetFiatMethods200ResponseDataDefaultLayout | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'methods': value['methods'],
    };
}

