/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PopularCategory } from './PopularCategory';
import {
    PopularCategoryFromJSON,
    PopularCategoryFromJSONTyped,
    PopularCategoryToJSON,
    PopularCategoryToJSONTyped,
} from './PopularCategory';
import type { PopularApp } from './PopularApp';
import {
    PopularAppFromJSON,
    PopularAppFromJSONTyped,
    PopularAppToJSON,
    PopularAppToJSONTyped,
} from './PopularApp';

/**
 * 
 * @export
 * @interface GetPopularApps200ResponseData
 */
export interface GetPopularApps200ResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof GetPopularApps200ResponseData
     */
    moreEnabled: boolean;
    /**
     * 
     * @type {Array<PopularCategory>}
     * @memberof GetPopularApps200ResponseData
     */
    categories: Array<PopularCategory>;
    /**
     * 
     * @type {Array<PopularApp>}
     * @memberof GetPopularApps200ResponseData
     */
    apps: Array<PopularApp>;
}

/**
 * Check if a given object implements the GetPopularApps200ResponseData interface.
 */
export function instanceOfGetPopularApps200ResponseData(value: object): value is GetPopularApps200ResponseData {
    if (!('moreEnabled' in value) || value['moreEnabled'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('apps' in value) || value['apps'] === undefined) return false;
    return true;
}

export function GetPopularApps200ResponseDataFromJSON(json: any): GetPopularApps200ResponseData {
    return GetPopularApps200ResponseDataFromJSONTyped(json, false);
}

export function GetPopularApps200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPopularApps200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'moreEnabled': json['moreEnabled'],
        'categories': ((json['categories'] as Array<any>).map(PopularCategoryFromJSON)),
        'apps': ((json['apps'] as Array<any>).map(PopularAppFromJSON)),
    };
}

export function GetPopularApps200ResponseDataToJSON(json: any): GetPopularApps200ResponseData {
    return GetPopularApps200ResponseDataToJSONTyped(json, false);
}

export function GetPopularApps200ResponseDataToJSONTyped(value?: GetPopularApps200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'moreEnabled': value['moreEnabled'],
        'categories': ((value['categories'] as Array<any>).map(PopularCategoryToJSON)),
        'apps': ((value['apps'] as Array<any>).map(PopularAppToJSON)),
    };
}

