/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WidgetRate } from './WidgetRate';
import {
    WidgetRateFromJSON,
    WidgetRateFromJSONTyped,
    WidgetRateToJSON,
    WidgetRateToJSONTyped,
} from './WidgetRate';

/**
 * 
 * @export
 * @interface GetSellRatesWidget200Response
 */
export interface GetSellRatesWidget200Response {
    /**
     * 
     * @type {Array<WidgetRate>}
     * @memberof GetSellRatesWidget200Response
     */
    items: Array<WidgetRate>;
}

/**
 * Check if a given object implements the GetSellRatesWidget200Response interface.
 */
export function instanceOfGetSellRatesWidget200Response(value: object): value is GetSellRatesWidget200Response {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GetSellRatesWidget200ResponseFromJSON(json: any): GetSellRatesWidget200Response {
    return GetSellRatesWidget200ResponseFromJSONTyped(json, false);
}

export function GetSellRatesWidget200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSellRatesWidget200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WidgetRateFromJSON)),
    };
}

export function GetSellRatesWidget200ResponseToJSON(json: any): GetSellRatesWidget200Response {
    return GetSellRatesWidget200ResponseToJSONTyped(json, false);
}

export function GetSellRatesWidget200ResponseToJSONTyped(value?: GetSellRatesWidget200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WidgetRateToJSON)),
    };
}

