/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StoryInfo } from './StoryInfo';
import {
    StoryInfoFromJSON,
    StoryInfoFromJSONTyped,
    StoryInfoToJSON,
    StoryInfoToJSONTyped,
} from './StoryInfo';

/**
 * 
 * @export
 * @interface GetStoriesBatch200Response
 */
export interface GetStoriesBatch200Response {
    /**
     * 
     * @type {Array<StoryInfo>}
     * @memberof GetStoriesBatch200Response
     */
    stories: Array<StoryInfo>;
}

/**
 * Check if a given object implements the GetStoriesBatch200Response interface.
 */
export function instanceOfGetStoriesBatch200Response(value: object): value is GetStoriesBatch200Response {
    if (!('stories' in value) || value['stories'] === undefined) return false;
    return true;
}

export function GetStoriesBatch200ResponseFromJSON(json: any): GetStoriesBatch200Response {
    return GetStoriesBatch200ResponseFromJSONTyped(json, false);
}

export function GetStoriesBatch200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStoriesBatch200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'stories': ((json['stories'] as Array<any>).map(StoryInfoFromJSON)),
    };
}

export function GetStoriesBatch200ResponseToJSON(json: any): GetStoriesBatch200Response {
    return GetStoriesBatch200ResponseToJSONTyped(json, false);
}

export function GetStoriesBatch200ResponseToJSONTyped(value?: GetStoriesBatch200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stories': ((value['stories'] as Array<any>).map(StoryInfoToJSON)),
    };
}

