/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Method = {
    MercuryoPro: 'mercuryo_pro',
    MercuryoNot: 'mercuryo_not',
    MercuryoNotSell: 'mercuryo_not_sell',
    MercuryoUsdt: 'mercuryo_usdt',
    MercuryoUsdtSell: 'mercuryo_usdt_sell',
    MercuryoUsdtTrc20: 'mercuryo_usdt_trc20',
    MercuryoUsdtTrc20Sell: 'mercuryo_usdt_trc20_sell',
    NeocryptoUsdt: 'neocrypto_usdt',
    NeocryptoUsdtSell: 'neocrypto_usdt_sell',
    MoonpayUsdt: 'moonpay_usdt',
    MoonpayUsdtSell: 'moonpay_usdt_sell',
    DreamwalkersUsdt: 'dreamwalkers_usdt',
    DreamwalkersUsdtSell: 'dreamwalkers_usdt_sell',
    Mercuryo: 'mercuryo',
    Neocrypto: 'neocrypto',
    WalletBot: 'wallet_bot',
    Dreamwalkers: 'dreamwalkers',
    DreamwalkersNot: 'dreamwalkers_not',
    Changelly: 'changelly',
    Transak: 'transak',
    TransakSell: 'transak_sell',
    TransakUsdt: 'transak_usdt',
    TransakUsdtSell: 'transak_usdt_sell',
    MercuryoSell: 'mercuryo_sell',
    _1nio: '1nio',
    Moonpay: 'moonpay',
    DreamwalkersSell: 'dreamwalkers_sell',
    DreamwalkersHamster: 'dreamwalkers_hamster',
    DreamwalkersHamsterSell: 'dreamwalkers_hamster_sell',
    ChangellySellSwap: 'changelly_sell_swap',
    ChangellyBuySwap: 'changelly_buy_swap',
    LetsexchangeBuySwap: 'letsexchange_buy_swap',
    LetsexchangeSellSwap: 'letsexchange_sell_swap',
    SimpleBuySwap: 'simple_buy_swap',
    SimpleSellSwap: 'simple_sell_swap',
    LetsExchange: 'letsExchange',
    SimpleSwap: 'simpleSwap'
} as const;
export type Method = typeof Method[keyof typeof Method];


export function instanceOfMethod(value: any): boolean {
    for (const key in Method) {
        if (Object.prototype.hasOwnProperty.call(Method, key)) {
            if (Method[key as keyof typeof Method] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MethodFromJSON(json: any): Method {
    return MethodFromJSONTyped(json, false);
}

export function MethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Method {
    return json as Method;
}

export function MethodToJSON(value?: Method | null): any {
    return value as any;
}

export function MethodToJSONTyped(value: any, ignoreDiscriminator: boolean): Method {
    return value as Method;
}

