/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Button } from './Button';
import {
    ButtonFromJSON,
    ButtonFromJSONTyped,
    ButtonToJSON,
    ButtonToJSONTyped,
} from './Button';

/**
 * 
 * @export
 * @interface PopularApp
 */
export interface PopularApp {
    /**
     * App identifier for client purposes
     * @type {string}
     * @memberof PopularApp
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PopularApp
     */
    bannerId?: string;
    /**
     * Application name
     * @type {string}
     * @memberof PopularApp
     */
    name: string;
    /**
     * Application description
     * @type {string}
     * @memberof PopularApp
     */
    description: string;
    /**
     * Icon URL
     * @type {string}
     * @memberof PopularApp
     */
    icon?: string;
    /**
     * Poster image URL
     * @type {string}
     * @memberof PopularApp
     */
    poster?: string;
    /**
     * Application URL
     * @type {string}
     * @memberof PopularApp
     */
    url?: string;
    /**
     * Countries where app is not available
     * @type {Array<string>}
     * @memberof PopularApp
     */
    excludeCountries?: Array<string>;
    /**
     * Countries where app is available (ISO 3166-1)
     * @type {Array<string>}
     * @memberof PopularApp
     */
    includeCountries?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PopularApp
     */
    textColor?: string;
    /**
     * 
     * @type {Button}
     * @memberof PopularApp
     */
    button?: Button;
}

/**
 * Check if a given object implements the PopularApp interface.
 */
export function instanceOfPopularApp(value: object): value is PopularApp {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PopularAppFromJSON(json: any): PopularApp {
    return PopularAppFromJSONTyped(json, false);
}

export function PopularAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): PopularApp {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bannerId': json['banner_id'] == null ? undefined : json['banner_id'],
        'name': json['name'],
        'description': json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'poster': json['poster'] == null ? undefined : json['poster'],
        'url': json['url'] == null ? undefined : json['url'],
        'excludeCountries': json['excludeCountries'] == null ? undefined : json['excludeCountries'],
        'includeCountries': json['includeCountries'] == null ? undefined : json['includeCountries'],
        'textColor': json['textColor'] == null ? undefined : json['textColor'],
        'button': json['button'] == null ? undefined : ButtonFromJSON(json['button']),
    };
}

export function PopularAppToJSON(json: any): PopularApp {
    return PopularAppToJSONTyped(json, false);
}

export function PopularAppToJSONTyped(value?: PopularApp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'banner_id': value['bannerId'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'poster': value['poster'],
        'url': value['url'],
        'excludeCountries': value['excludeCountries'],
        'includeCountries': value['includeCountries'],
        'textColor': value['textColor'],
        'button': ButtonToJSON(value['button']),
    };
}

