/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Button } from './Button';
import {
    ButtonFromJSON,
    ButtonFromJSONTyped,
    ButtonToJSON,
    ButtonToJSONTyped,
} from './Button';

/**
 * 
 * @export
 * @interface StoryPage
 */
export interface StoryPage {
    /**
     * 
     * @type {string}
     * @memberof StoryPage
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof StoryPage
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof StoryPage
     */
    image: string;
    /**
     * 
     * @type {Array<StoryPageIncludeWalletsEnum>}
     * @memberof StoryPage
     */
    includeWallets: Array<StoryPageIncludeWalletsEnum>;
    /**
     * 
     * @type {Button}
     * @memberof StoryPage
     */
    button?: Button;
    /**
     * 
     * @type {Array<Button>}
     * @memberof StoryPage
     */
    buttons?: Array<Button>;
}


/**
 * @export
 */
export const StoryPageIncludeWalletsEnum = {
    Ledger: 'ledger',
    Keystone: 'keystone',
    Signer: 'signer',
    WatchOnly: 'watch-only',
    Imported: 'imported'
} as const;
export type StoryPageIncludeWalletsEnum = typeof StoryPageIncludeWalletsEnum[keyof typeof StoryPageIncludeWalletsEnum];


/**
 * Check if a given object implements the StoryPage interface.
 */
export function instanceOfStoryPage(value: object): value is StoryPage {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('includeWallets' in value) || value['includeWallets'] === undefined) return false;
    return true;
}

export function StoryPageFromJSON(json: any): StoryPage {
    return StoryPageFromJSONTyped(json, false);
}

export function StoryPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoryPage {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'image': json['image'],
        'includeWallets': json['include_wallets'],
        'button': json['button'] == null ? undefined : ButtonFromJSON(json['button']),
        'buttons': json['buttons'] == null ? undefined : ((json['buttons'] as Array<any>).map(ButtonFromJSON)),
    };
}

export function StoryPageToJSON(json: any): StoryPage {
    return StoryPageToJSONTyped(json, false);
}

export function StoryPageToJSONTyped(value?: StoryPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'image': value['image'],
        'include_wallets': value['includeWallets'],
        'button': ButtonToJSON(value['button']),
        'buttons': value['buttons'] == null ? undefined : ((value['buttons'] as Array<any>).map(ButtonToJSON)),
    };
}

