/* tslint:disable */
/* eslint-disable */
/**
 * gasless TRON service REST api
 * Service to publish TRON transactions
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractDeployAction
 */
export interface ContractDeployAction {
    /**
     * 
     * @type {string}
     * @memberof ContractDeployAction
     */
    ownerAddress: string;
}

/**
 * Check if a given object implements the ContractDeployAction interface.
 */
export function instanceOfContractDeployAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ownerAddress" in value;

    return isInstance;
}

export function ContractDeployActionFromJSON(json: any): ContractDeployAction {
    return ContractDeployActionFromJSONTyped(json, false);
}

export function ContractDeployActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractDeployAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ownerAddress': json['ownerAddress'],
    };
}

export function ContractDeployActionToJSON(value?: ContractDeployAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ownerAddress': value.ownerAddress,
    };
}

