/* tslint:disable */
/* eslint-disable */
/**
 * gasless TRON service REST api
 * Service to publish TRON transactions
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FromMessage } from './FromMessage';
import {
    FromMessageFromJSON,
    FromMessageFromJSONTyped,
    FromMessageToJSON,
} from './FromMessage';

/**
 * 
 * @export
 * @interface GetEstimationRequest
 */
export interface GetEstimationRequest {
    /**
     * 
     * @type {number}
     * @memberof GetEstimationRequest
     */
    lifeTime: number;
    /**
     * 
     * @type {Array<FromMessage>}
     * @memberof GetEstimationRequest
     */
    messages: Array<FromMessage>;
}

/**
 * Check if a given object implements the GetEstimationRequest interface.
 */
export function instanceOfGetEstimationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lifeTime" in value;
    isInstance = isInstance && "messages" in value;

    return isInstance;
}

export function GetEstimationRequestFromJSON(json: any): GetEstimationRequest {
    return GetEstimationRequestFromJSONTyped(json, false);
}

export function GetEstimationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEstimationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lifeTime': json['lifeTime'],
        'messages': ((json['messages'] as Array<any>).map(FromMessageFromJSON)),
    };
}

export function GetEstimationRequestToJSON(value?: GetEstimationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lifeTime': value.lifeTime,
        'messages': ((value.messages as Array<any>).map(FromMessageToJSON)),
    };
}

