/* tslint:disable */
/* eslint-disable */
/**
 * gasless TRON service REST api
 * Service to publish TRON transactions
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSettings401Response
 */
export interface GetSettings401Response {
    /**
     * 
     * @type {string}
     * @memberof GetSettings401Response
     */
    error: string;
}

/**
 * Check if a given object implements the GetSettings401Response interface.
 */
export function instanceOfGetSettings401Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function GetSettings401ResponseFromJSON(json: any): GetSettings401Response {
    return GetSettings401ResponseFromJSONTyped(json, false);
}

export function GetSettings401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSettings401Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function GetSettings401ResponseToJSON(value?: GetSettings401Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

