/* tslint:disable */
/* eslint-disable */
/**
 * gasless TRON service REST api
 * Service to publish TRON transactions
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TronToken } from './TronToken';
import {
    TronTokenFromJSON,
    TronTokenFromJSONTyped,
    TronTokenToJSON,
} from './TronToken';

/**
 * 
 * @export
 * @interface TronBalance
 */
export interface TronBalance {
    /**
     * 
     * @type {TronToken}
     * @memberof TronBalance
     */
    token: TronToken;
    /**
     * 
     * @type {string}
     * @memberof TronBalance
     */
    weiAmount: string;
}

/**
 * Check if a given object implements the TronBalance interface.
 */
export function instanceOfTronBalance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "weiAmount" in value;

    return isInstance;
}

export function TronBalanceFromJSON(json: any): TronBalance {
    return TronBalanceFromJSONTyped(json, false);
}

export function TronBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TronBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': TronTokenFromJSON(json['token']),
        'weiAmount': json['weiAmount'],
    };
}

export function TronBalanceToJSON(value?: TronBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': TronTokenToJSON(value.token),
        'weiAmount': value.weiAmount,
    };
}

