/* tslint:disable */
/* eslint-disable */
/**
 * REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Proof } from './Proof';
import {
    ProofFromJSON,
    ProofFromJSONTyped,
    ProofToJSON,
    ProofToJSONTyped,
} from './Proof';

/**
 * 
 * @export
 * @interface ConnectRequest
 */
export interface ConnectRequest {
    /**
     * 
     * @type {string}
     * @memberof ConnectRequest
     */
    address: string;
    /**
     * 
     * @type {Proof}
     * @memberof ConnectRequest
     */
    proof: Proof;
}

/**
 * Check if a given object implements the ConnectRequest interface.
 */
export function instanceOfConnectRequest(value: object): value is ConnectRequest {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('proof' in value) || value['proof'] === undefined) return false;
    return true;
}

export function ConnectRequestFromJSON(json: any): ConnectRequest {
    return ConnectRequestFromJSONTyped(json, false);
}

export function ConnectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'proof': ProofFromJSON(json['proof']),
    };
}

  export function ConnectRequestToJSON(json: any): ConnectRequest {
      return ConnectRequestToJSONTyped(json, false);
  }

  export function ConnectRequestToJSONTyped(value?: ConnectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'proof': ProofToJSON(value['proof']),
    };
}

