/* tslint:disable */
/* eslint-disable */
/**
 * REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMessageRequest
 */
export interface SendMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    wallet: string;
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    stateInit: string;
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    dataToSign: string;
    /**
     * 
     * @type {string}
     * @memberof SendMessageRequest
     */
    signature: string;
}

/**
 * Check if a given object implements the SendMessageRequest interface.
 */
export function instanceOfSendMessageRequest(value: object): value is SendMessageRequest {
    if (!('wallet' in value) || value['wallet'] === undefined) return false;
    if (!('stateInit' in value) || value['stateInit'] === undefined) return false;
    if (!('dataToSign' in value) || value['dataToSign'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function SendMessageRequestFromJSON(json: any): SendMessageRequest {
    return SendMessageRequestFromJSONTyped(json, false);
}

export function SendMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'wallet': json['wallet'],
        'stateInit': json['state_init'],
        'dataToSign': json['data_to_sign'],
        'signature': json['signature'],
    };
}

  export function SendMessageRequestToJSON(json: any): SendMessageRequest {
      return SendMessageRequestToJSONTyped(json, false);
  }

  export function SendMessageRequestToJSONTyped(value?: SendMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wallet': value['wallet'],
        'state_init': value['stateInit'],
        'data_to_sign': value['dataToSign'],
        'signature': value['signature'],
    };
}

