/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AccountStatus = {
    Nonexist: 'nonexist',
    Uninit: 'uninit',
    Active: 'active',
    Frozen: 'frozen'
} as const;
export type AccountStatus = typeof AccountStatus[keyof typeof AccountStatus];


export function instanceOfAccountStatus(value: any): boolean {
    for (const key in AccountStatus) {
        if (Object.prototype.hasOwnProperty.call(AccountStatus, key)) {
            if (AccountStatus[key as keyof typeof AccountStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccountStatusFromJSON(json: any): AccountStatus {
    return AccountStatusFromJSONTyped(json, false);
}

export function AccountStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStatus {
    return json as AccountStatus;
}

export function AccountStatusToJSON(value?: AccountStatus | null): any {
    return value as any;
}

export function AccountStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AccountStatus {
    return value as AccountStatus;
}

