/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AndroidBatteryPurchaseStatusPurchasesInnerError
 */
export interface AndroidBatteryPurchaseStatusPurchasesInnerError {
    /**
     * 
     * @type {string}
     * @memberof AndroidBatteryPurchaseStatusPurchasesInnerError
     */
    msg: string;
    /**
     * 
     * @type {string}
     * @memberof AndroidBatteryPurchaseStatusPurchasesInnerError
     */
    code: AndroidBatteryPurchaseStatusPurchasesInnerErrorCodeEnum;
}


/**
 * @export
 */
export const AndroidBatteryPurchaseStatusPurchasesInnerErrorCodeEnum = {
    InvalidProductId: 'invalid-product-id',
    UserNotFound: 'user-not-found',
    PurchaseIsAlreadyUsed: 'purchase-is-already-used',
    TemporaryError: 'temporary-error',
    Unknown: 'unknown'
} as const;
export type AndroidBatteryPurchaseStatusPurchasesInnerErrorCodeEnum = typeof AndroidBatteryPurchaseStatusPurchasesInnerErrorCodeEnum[keyof typeof AndroidBatteryPurchaseStatusPurchasesInnerErrorCodeEnum];


/**
 * Check if a given object implements the AndroidBatteryPurchaseStatusPurchasesInnerError interface.
 */
export function instanceOfAndroidBatteryPurchaseStatusPurchasesInnerError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "msg" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function AndroidBatteryPurchaseStatusPurchasesInnerErrorFromJSON(json: any): AndroidBatteryPurchaseStatusPurchasesInnerError {
    return AndroidBatteryPurchaseStatusPurchasesInnerErrorFromJSONTyped(json, false);
}

export function AndroidBatteryPurchaseStatusPurchasesInnerErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AndroidBatteryPurchaseStatusPurchasesInnerError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msg': json['msg'],
        'code': json['code'],
    };
}

export function AndroidBatteryPurchaseStatusPurchasesInnerErrorToJSON(value?: AndroidBatteryPurchaseStatusPurchasesInnerError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msg': value.msg,
        'code': value.code,
    };
}

