/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyPromoRequest
 */
export interface ApplyPromoRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplyPromoRequest
     */
    publicKey: string;
    /**
     * 
     * @type {string}
     * @memberof ApplyPromoRequest
     */
    promoCode: string;
}

/**
 * Check if a given object implements the ApplyPromoRequest interface.
 */
export function instanceOfApplyPromoRequest(value: object): value is ApplyPromoRequest {
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    if (!('promoCode' in value) || value['promoCode'] === undefined) return false;
    return true;
}

export function ApplyPromoRequestFromJSON(json: any): ApplyPromoRequest {
    return ApplyPromoRequestFromJSONTyped(json, false);
}

export function ApplyPromoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyPromoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'publicKey': json['public_key'],
        'promoCode': json['promo_code'],
    };
}

  export function ApplyPromoRequestToJSON(json: any): ApplyPromoRequest {
      return ApplyPromoRequestToJSONTyped(json, false);
  }

  export function ApplyPromoRequestToJSONTyped(value?: ApplyPromoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_key': value['publicKey'],
        'promo_code': value['promoCode'],
    };
}

