/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockParamLimits
 */
export interface BlockParamLimits {
    /**
     * 
     * @type {number}
     * @memberof BlockParamLimits
     */
    underload: number;
    /**
     * 
     * @type {number}
     * @memberof BlockParamLimits
     */
    softLimit: number;
    /**
     * 
     * @type {number}
     * @memberof BlockParamLimits
     */
    hardLimit: number;
}

/**
 * Check if a given object implements the BlockParamLimits interface.
 */
export function instanceOfBlockParamLimits(value: object): value is BlockParamLimits {
    if (!('underload' in value) || value['underload'] === undefined) return false;
    if (!('softLimit' in value) || value['softLimit'] === undefined) return false;
    if (!('hardLimit' in value) || value['hardLimit'] === undefined) return false;
    return true;
}

export function BlockParamLimitsFromJSON(json: any): BlockParamLimits {
    return BlockParamLimitsFromJSONTyped(json, false);
}

export function BlockParamLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockParamLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'underload': json['underload'],
        'softLimit': json['soft_limit'],
        'hardLimit': json['hard_limit'],
    };
}

  export function BlockParamLimitsToJSON(json: any): BlockParamLimits {
      return BlockParamLimitsToJSONTyped(json, false);
  }

  export function BlockParamLimitsToJSONTyped(value?: BlockParamLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'underload': value['underload'],
        'soft_limit': value['softLimit'],
        'hard_limit': value['hardLimit'],
    };
}

