/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockchainRawAccountLibrariesInner
 */
export interface BlockchainRawAccountLibrariesInner {
    /**
     * 
     * @type {boolean}
     * @memberof BlockchainRawAccountLibrariesInner
     */
    _public: boolean;
    /**
     * 
     * @type {string}
     * @memberof BlockchainRawAccountLibrariesInner
     */
    root: string;
}

/**
 * Check if a given object implements the BlockchainRawAccountLibrariesInner interface.
 */
export function instanceOfBlockchainRawAccountLibrariesInner(value: object): value is BlockchainRawAccountLibrariesInner {
    if (!('_public' in value) || value['_public'] === undefined) return false;
    if (!('root' in value) || value['root'] === undefined) return false;
    return true;
}

export function BlockchainRawAccountLibrariesInnerFromJSON(json: any): BlockchainRawAccountLibrariesInner {
    return BlockchainRawAccountLibrariesInnerFromJSONTyped(json, false);
}

export function BlockchainRawAccountLibrariesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainRawAccountLibrariesInner {
    if (json == null) {
        return json;
    }
    return {
        
        '_public': json['public'],
        'root': json['root'],
    };
}

  export function BlockchainRawAccountLibrariesInnerToJSON(json: any): BlockchainRawAccountLibrariesInner {
      return BlockchainRawAccountLibrariesInnerToJSONTyped(json, false);
  }

  export function BlockchainRawAccountLibrariesInnerToJSONTyped(value?: BlockchainRawAccountLibrariesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public': value['_public'],
        'root': value['root'],
    };
}

