/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BouncePhaseType = {
    TrPhaseBounceNegfunds: 'TrPhaseBounceNegfunds',
    TrPhaseBounceNofunds: 'TrPhaseBounceNofunds',
    TrPhaseBounceOk: 'TrPhaseBounceOk'
} as const;
export type BouncePhaseType = typeof BouncePhaseType[keyof typeof BouncePhaseType];


export function instanceOfBouncePhaseType(value: any): boolean {
    for (const key in BouncePhaseType) {
        if (Object.prototype.hasOwnProperty.call(BouncePhaseType, key)) {
            if (BouncePhaseType[key as keyof typeof BouncePhaseType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BouncePhaseTypeFromJSON(json: any): BouncePhaseType {
    return BouncePhaseTypeFromJSONTyped(json, false);
}

export function BouncePhaseTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BouncePhaseType {
    return json as BouncePhaseType;
}

export function BouncePhaseTypeToJSON(value?: BouncePhaseType | null): any {
    return value as any;
}

export function BouncePhaseTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BouncePhaseType {
    return value as BouncePhaseType;
}

