/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePromoCampaignRequestParticipantsInner
 */
export interface CreatePromoCampaignRequestParticipantsInner {
    /**
     * 
     * @type {string}
     * @memberof CreatePromoCampaignRequestParticipantsInner
     */
    address: string;
    /**
     * amount in TON
     * @type {string}
     * @memberof CreatePromoCampaignRequestParticipantsInner
     */
    amount: string;
}

/**
 * Check if a given object implements the CreatePromoCampaignRequestParticipantsInner interface.
 */
export function instanceOfCreatePromoCampaignRequestParticipantsInner(value: object): value is CreatePromoCampaignRequestParticipantsInner {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreatePromoCampaignRequestParticipantsInnerFromJSON(json: any): CreatePromoCampaignRequestParticipantsInner {
    return CreatePromoCampaignRequestParticipantsInnerFromJSONTyped(json, false);
}

export function CreatePromoCampaignRequestParticipantsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePromoCampaignRequestParticipantsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'amount': json['amount'],
    };
}

  export function CreatePromoCampaignRequestParticipantsInnerToJSON(json: any): CreatePromoCampaignRequestParticipantsInner {
      return CreatePromoCampaignRequestParticipantsInnerToJSONTyped(json, false);
  }

  export function CreatePromoCampaignRequestParticipantsInnerToJSONTyped(value?: CreatePromoCampaignRequestParticipantsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'amount': value['amount'],
    };
}

