/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditPhase
 */
export interface CreditPhase {
    /**
     * 
     * @type {number}
     * @memberof CreditPhase
     */
    feesCollected: number;
    /**
     * 
     * @type {number}
     * @memberof CreditPhase
     */
    credit: number;
}

/**
 * Check if a given object implements the CreditPhase interface.
 */
export function instanceOfCreditPhase(value: object): value is CreditPhase {
    if (!('feesCollected' in value) || value['feesCollected'] === undefined) return false;
    if (!('credit' in value) || value['credit'] === undefined) return false;
    return true;
}

export function CreditPhaseFromJSON(json: any): CreditPhase {
    return CreditPhaseFromJSONTyped(json, false);
}

export function CreditPhaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditPhase {
    if (json == null) {
        return json;
    }
    return {
        
        'feesCollected': json['fees_collected'],
        'credit': json['credit'],
    };
}

  export function CreditPhaseToJSON(json: any): CreditPhase {
      return CreditPhaseToJSONTyped(json, false);
  }

  export function CreditPhaseToJSONTyped(value?: CreditPhase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fees_collected': value['feesCollected'],
        'credit': value['credit'],
    };
}

