/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountAddress } from './AccountAddress';
import {
    AccountAddressFromJSON,
    AccountAddressFromJSONTyped,
    AccountAddressToJSON,
    AccountAddressToJSONTyped,
} from './AccountAddress';

/**
 * 
 * @export
 * @interface ElectionsDepositStakeAction
 */
export interface ElectionsDepositStakeAction {
    /**
     * 
     * @type {number}
     * @memberof ElectionsDepositStakeAction
     */
    amount: number;
    /**
     * 
     * @type {AccountAddress}
     * @memberof ElectionsDepositStakeAction
     */
    staker: AccountAddress;
}

/**
 * Check if a given object implements the ElectionsDepositStakeAction interface.
 */
export function instanceOfElectionsDepositStakeAction(value: object): value is ElectionsDepositStakeAction {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('staker' in value) || value['staker'] === undefined) return false;
    return true;
}

export function ElectionsDepositStakeActionFromJSON(json: any): ElectionsDepositStakeAction {
    return ElectionsDepositStakeActionFromJSONTyped(json, false);
}

export function ElectionsDepositStakeActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElectionsDepositStakeAction {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'staker': AccountAddressFromJSON(json['staker']),
    };
}

  export function ElectionsDepositStakeActionToJSON(json: any): ElectionsDepositStakeAction {
      return ElectionsDepositStakeActionToJSONTyped(json, false);
  }

  export function ElectionsDepositStakeActionToJSONTyped(value?: ElectionsDepositStakeAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'staker': AccountAddressToJSON(value['staker']),
    };
}

