/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnterpriseGetMessage200Response
 */
export interface EnterpriseGetMessage200Response {
    /**
     * 
     * @type {string}
     * @memberof EnterpriseGetMessage200Response
     */
    paymentTxHash?: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseGetMessage200Response
     */
    committedTxHash?: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseGetMessage200Response
     */
    status: EnterpriseGetMessage200ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseGetMessage200Response
     */
    finalCost?: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseGetMessage200Response
     */
    failedReason?: string;
}


/**
 * @export
 */
export const EnterpriseGetMessage200ResponseStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type EnterpriseGetMessage200ResponseStatusEnum = typeof EnterpriseGetMessage200ResponseStatusEnum[keyof typeof EnterpriseGetMessage200ResponseStatusEnum];


/**
 * Check if a given object implements the EnterpriseGetMessage200Response interface.
 */
export function instanceOfEnterpriseGetMessage200Response(value: object): value is EnterpriseGetMessage200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function EnterpriseGetMessage200ResponseFromJSON(json: any): EnterpriseGetMessage200Response {
    return EnterpriseGetMessage200ResponseFromJSONTyped(json, false);
}

export function EnterpriseGetMessage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnterpriseGetMessage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentTxHash': json['payment_tx_hash'] == null ? undefined : json['payment_tx_hash'],
        'committedTxHash': json['committed_tx_hash'] == null ? undefined : json['committed_tx_hash'],
        'status': json['status'],
        'finalCost': json['final_cost'] == null ? undefined : json['final_cost'],
        'failedReason': json['failed_reason'] == null ? undefined : json['failed_reason'],
    };
}

  export function EnterpriseGetMessage200ResponseToJSON(json: any): EnterpriseGetMessage200Response {
      return EnterpriseGetMessage200ResponseToJSONTyped(json, false);
  }

  export function EnterpriseGetMessage200ResponseToJSONTyped(value?: EnterpriseGetMessage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_tx_hash': value['paymentTxHash'],
        'committed_tx_hash': value['committedTxHash'],
        'status': value['status'],
        'final_cost': value['finalCost'],
        'failed_reason': value['failedReason'],
    };
}

