/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GaslessEstimation
 */
export interface GaslessEstimation {
    /**
     * 
     * @type {string}
     * @memberof GaslessEstimation
     */
    commission: string;
}

/**
 * Check if a given object implements the GaslessEstimation interface.
 */
export function instanceOfGaslessEstimation(value: object): value is GaslessEstimation {
    if (!('commission' in value) || value['commission'] === undefined) return false;
    return true;
}

export function GaslessEstimationFromJSON(json: any): GaslessEstimation {
    return GaslessEstimationFromJSONTyped(json, false);
}

export function GaslessEstimationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GaslessEstimation {
    if (json == null) {
        return json;
    }
    return {
        
        'commission': json['commission'],
    };
}

  export function GaslessEstimationToJSON(json: any): GaslessEstimation {
      return GaslessEstimationToJSONTyped(json, false);
  }

  export function GaslessEstimationToJSONTyped(value?: GaslessEstimation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commission': value['commission'],
    };
}

