/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncreaseUserBalanceRequest
 */
export interface IncreaseUserBalanceRequest {
    /**
     * amount in TON to increase balance by
     * @type {string}
     * @memberof IncreaseUserBalanceRequest
     */
    amount: string;
    /**
     * reason for balance increase
     * @type {string}
     * @memberof IncreaseUserBalanceRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the IncreaseUserBalanceRequest interface.
 */
export function instanceOfIncreaseUserBalanceRequest(value: object): value is IncreaseUserBalanceRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function IncreaseUserBalanceRequestFromJSON(json: any): IncreaseUserBalanceRequest {
    return IncreaseUserBalanceRequestFromJSONTyped(json, false);
}

export function IncreaseUserBalanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncreaseUserBalanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

  export function IncreaseUserBalanceRequestToJSON(json: any): IncreaseUserBalanceRequest {
      return IncreaseUserBalanceRequestToJSONTyped(json, false);
  }

  export function IncreaseUserBalanceRequestToJSONTyped(value?: IncreaseUserBalanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'reason': value['reason'],
    };
}

