/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InscriptionBalance } from './InscriptionBalance';
import {
    InscriptionBalanceFromJSON,
    InscriptionBalanceFromJSONTyped,
    InscriptionBalanceToJSON,
    InscriptionBalanceToJSONTyped,
} from './InscriptionBalance';

/**
 * 
 * @export
 * @interface InscriptionBalances
 */
export interface InscriptionBalances {
    /**
     * 
     * @type {Array<InscriptionBalance>}
     * @memberof InscriptionBalances
     */
    inscriptions: Array<InscriptionBalance>;
}

/**
 * Check if a given object implements the InscriptionBalances interface.
 */
export function instanceOfInscriptionBalances(value: object): value is InscriptionBalances {
    if (!('inscriptions' in value) || value['inscriptions'] === undefined) return false;
    return true;
}

export function InscriptionBalancesFromJSON(json: any): InscriptionBalances {
    return InscriptionBalancesFromJSONTyped(json, false);
}

export function InscriptionBalancesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InscriptionBalances {
    if (json == null) {
        return json;
    }
    return {
        
        'inscriptions': ((json['inscriptions'] as Array<any>).map(InscriptionBalanceFromJSON)),
    };
}

  export function InscriptionBalancesToJSON(json: any): InscriptionBalances {
      return InscriptionBalancesToJSONTyped(json, false);
  }

  export function InscriptionBalancesToJSONTyped(value?: InscriptionBalances | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inscriptions': ((value['inscriptions'] as Array<any>).map(InscriptionBalanceToJSON)),
    };
}

