/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JettonBalanceLock
 */
export interface JettonBalanceLock {
    /**
     * 
     * @type {string}
     * @memberof JettonBalanceLock
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof JettonBalanceLock
     */
    till: number;
}

/**
 * Check if a given object implements the JettonBalanceLock interface.
 */
export function instanceOfJettonBalanceLock(value: object): value is JettonBalanceLock {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('till' in value) || value['till'] === undefined) return false;
    return true;
}

export function JettonBalanceLockFromJSON(json: any): JettonBalanceLock {
    return JettonBalanceLockFromJSONTyped(json, false);
}

export function JettonBalanceLockFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettonBalanceLock {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'till': json['till'],
    };
}

  export function JettonBalanceLockToJSON(json: any): JettonBalanceLock {
      return JettonBalanceLockToJSONTyped(json, false);
  }

  export function JettonBalanceLockToJSONTyped(value?: JettonBalanceLock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'till': value['till'],
    };
}

