/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * hex encoded bytes
     * @type {string}
     * @memberof Metadata
     */
    encryptedBinary: string;
    /**
     * hex encoded bytes
     * @type {string}
     * @memberof Metadata
     */
    decryptionKey?: string;
}

/**
 * Check if a given object implements the Metadata interface.
 */
export function instanceOfMetadata(value: object): value is Metadata {
    if (!('encryptedBinary' in value) || value['encryptedBinary'] === undefined) return false;
    return true;
}

export function MetadataFromJSON(json: any): Metadata {
    return MetadataFromJSONTyped(json, false);
}

export function MetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Metadata {
    if (json == null) {
        return json;
    }
    return {
        
        'encryptedBinary': json['encrypted_binary'],
        'decryptionKey': json['decryption_key'] == null ? undefined : json['decryption_key'],
    };
}

  export function MetadataToJSON(json: any): Metadata {
      return MetadataToJSONTyped(json, false);
  }

  export function MetadataToJSONTyped(value?: Metadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'encrypted_binary': value['encryptedBinary'],
        'decryption_key': value['decryptionKey'],
    };
}

