/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawBlockchainConfig
 */
export interface RawBlockchainConfig {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RawBlockchainConfig
     */
    config: { [key: string]: any; };
}

/**
 * Check if a given object implements the RawBlockchainConfig interface.
 */
export function instanceOfRawBlockchainConfig(value: object): value is RawBlockchainConfig {
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function RawBlockchainConfigFromJSON(json: any): RawBlockchainConfig {
    return RawBlockchainConfigFromJSONTyped(json, false);
}

export function RawBlockchainConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawBlockchainConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'],
    };
}

  export function RawBlockchainConfigToJSON(json: any): RawBlockchainConfig {
      return RawBlockchainConfigToJSONTyped(json, false);
  }

  export function RawBlockchainConfigToJSONTyped(value?: RawBlockchainConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
    };
}

