/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestRefundRequest
 */
export interface RequestRefundRequest {
    /**
     * 
     * @type {number}
     * @memberof RequestRefundRequest
     * @deprecated
     */
    userPurchaseId?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestRefundRequest
     */
    purchaseId?: number;
}

/**
 * Check if a given object implements the RequestRefundRequest interface.
 */
export function instanceOfRequestRefundRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestRefundRequestFromJSON(json: any): RequestRefundRequest {
    return RequestRefundRequestFromJSONTyped(json, false);
}

export function RequestRefundRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRefundRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userPurchaseId': !exists(json, 'user_purchase_id') ? undefined : json['user_purchase_id'],
        'purchaseId': !exists(json, 'purchase_id') ? undefined : json['purchase_id'],
    };
}

export function RequestRefundRequestToJSON(value?: RequestRefundRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_purchase_id': value.userPurchaseId,
        'purchase_id': value.purchaseId,
    };
}

