/* tslint:disable */
/* eslint-disable */
/**
 * Custodial-Battery REST API.
 * REST API for Custodial Battery which provides gas to different networks to help execute transactions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@tonkeeper.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetUserBalanceRequest
 */
export interface ResetUserBalanceRequest {
    /**
     * 
     * @type {string}
     * @memberof ResetUserBalanceRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the ResetUserBalanceRequest interface.
 */
export function instanceOfResetUserBalanceRequest(value: object): value is ResetUserBalanceRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function ResetUserBalanceRequestFromJSON(json: any): ResetUserBalanceRequest {
    return ResetUserBalanceRequestFromJSONTyped(json, false);
}

export function ResetUserBalanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetUserBalanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

  export function ResetUserBalanceRequestToJSON(json: any): ResetUserBalanceRequest {
      return ResetUserBalanceRequestToJSONTyped(json, false);
  }

  export function ResetUserBalanceRequestToJSONTyped(value?: ResetUserBalanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

