/* tslint:disable */
/* eslint-disable */
/**
 * REST API to Ton Endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@tonaps.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetStakingEthenaMethods200Response,
  PingReadyGet500Response,
} from '../models/index';
import {
    GetStakingEthenaMethods200ResponseFromJSON,
    GetStakingEthenaMethods200ResponseToJSON,
    PingReadyGet500ResponseFromJSON,
    PingReadyGet500ResponseToJSON,
} from '../models/index';

export interface GetStakingEthenaMethodsRequest {
    address: string;
    lang?: string;
}

/**
 * EthenaApi - interface
 * 
 * @export
 * @interface EthenaApiInterface
 */
export interface EthenaApiInterface {
    /**
     * Creates request options for getStakingEthenaMethods without sending the request
     * @param {string} address Address
     * @param {string} [lang] Language code
     * @throws {RequiredError}
     * @memberof EthenaApiInterface
     */
    getStakingEthenaMethodsRequestOpts(requestParameters: GetStakingEthenaMethodsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} address Address
     * @param {string} [lang] Language code
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EthenaApiInterface
     */
    getStakingEthenaMethodsRaw(requestParameters: GetStakingEthenaMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStakingEthenaMethods200Response>>;

    /**
     */
    getStakingEthenaMethods(requestParameters: GetStakingEthenaMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStakingEthenaMethods200Response>;

}

/**
 * 
 */
export class EthenaApi extends runtime.BaseAPI implements EthenaApiInterface {

    /**
     * Creates request options for getStakingEthenaMethods without sending the request
     */
    async getStakingEthenaMethodsRequestOpts(requestParameters: GetStakingEthenaMethodsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling getStakingEthenaMethods().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/staking/ethena`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getStakingEthenaMethodsRaw(requestParameters: GetStakingEthenaMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStakingEthenaMethods200Response>> {
        const requestOptions = await this.getStakingEthenaMethodsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStakingEthenaMethods200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getStakingEthenaMethods(requestParameters: GetStakingEthenaMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStakingEthenaMethods200Response> {
        const response = await this.getStakingEthenaMethodsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
