name: Tonkeeper UI Showcase Production Deploy

on:
    push:
        branches: [main]
        paths:
            - 'apps/ui-showcase/**'
            - 'packages/ui-kit/**'
            - '.github/workflows/showcase-deploy.yaml'
            - '.github/workflows/showcase-production.yaml'
            - '.yarnrc.yml'
            - 'package.json'
            - 'yarn.lock'

jobs:
    showcase-deploy:
        uses: ./.github/workflows/showcase-deploy.yaml
        with:
            branch: main
        secrets: inherit
